### ISSUE TITLE
NPE when attempting to connect using websockets

### ISSUE THREAD

**Issue by MaeveOReilly** [ibm-messaging/iot-device-samples#16]
#In device.properties I add:
WebSocket = true

When I run the sample I now get an NPE:
~/java_iotp/iot-device-samples-master/java/device-samples $ mvn exec:java -Dexec.mainClass="com.ibm.iotf.sample.client.device.DeviceEventPublishthCounter"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ibmiot-device-samples 0.2.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ ibmiot-device-samples ---
Dec 07, 2016 1:07:52 AM com.ibm.iotf.client.AbstractClient createClient
INFO: com.ibm.iotf.sample.client.device.DeviceEventPublishWithCounter.main(): Org ID    = xxx
         Client ID    = d:xxx:xxx:xxx
Dec 07, 2016 1:07:53 AM com.ibm.iotf.client.AbstractClient connect
INFO: com.ibm.iotf.sample.client.device.DeviceEventPublishWithCounter.main(): Connecting client d:xxx:xxx:xxx to wss://xxx.messaging.internetofthings.ibmcloud.com:443 (attempt #1)...
MqttException (0) - java.lang.NullPointerException
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:133)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:74)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:77)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
        ... 1 more

Set WebSocket = false and it works but is on ssl://xxx:8883.  It should work on wss://xxx:443.

**Comment by jpwsutton** [comment]
This the result of a bug in the master version of the Paho Java client: https://github.com/eclipse/paho.mqtt.java/issues/234

The Sec-WebSocket-Key is one character too short and the IBM MessageSight server (quite rightly) rejects the connection. This has been fixed in the develop branch and is currently available in the SNAPSHOT builds. However this will need to be fixed in https://github.com/ibm-watson-iot/iot-java in order to make it down to this client.

**Comment by jpwsutton** [comment]
The java client has had a service release and this fix is now available in version v1.1.1

**Comment by sathipal** [comment]
@MaeveOReilly Can you verify the issue as we have updated the iot-java library to pickup the latest phao library v1.1.1

**Comment by MaeveOReilly** [comment]
@sathipal I had to update this in the pom.xml to 0.2.4:

**Comment by MaeveOReilly** [comment]
@sathipal  I had another look at this today and I think it's a different issue.  I will log it as such.  Also I see you updated pom.xml for this, thanks.  Closing.
